### ISSUE TITLE
Unable to connect to RabbitMQ using the example deployment

### ISSUE THREAD

**Issue by VenkateshSrini** [kedacore/sample-go-rabbitmq#18]
Hi,
I have created a keda sample at https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq using .NET core which is very similar to the GO Example given here. I have used the bitnami and have installed tried both the install methods 
`helm install rabbitmq --set auth.username=user --set auth.password=PASSWORD bitnami/rabbitmq` and also 
`helm install rabbitmq --set auth.username=user --set auth.password=PASSWORD --set volumePermissions.enabled=true bitnami/rabbitmq`

When I execute the command `kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}"` and I got the base 64 encoded equivalent of the "PASSWORD". But when i did a port forward of 15672 and I accessed http://localhost:15672. When I tried with user id as User and password as "PASSWORD". **But  I get login failed**.

**I get the below error PLAIN login refused: user 'user' - invalid credentials
2020-10-18 12:37:26.574 [info] <0.1053.0> closing AMQP connection <0.1053.0> (10.1.0.16:33184 -> 10.1.0.30:5672)
2020-10-18 12:37:26.574 [info] <0.1056.0> closing AMQP connection <0.1056.0> (10.1.0.16:33182 -> 10.1.0.30:5672)
2020-10-18 12:37:31.581 [info] <0.1067.0> accepting AMQP connection <0.1067.0> (10.1.0.16:33232 -> 10.1.0.30:5672)**

I tried to apply https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/blob/master/deploy/deploy-publisher-job.yaml. I get the below error 
**Unhandled Exception: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at Send.Send.Main(String[] args) in C:\Venkatesh\ASPNETCore10\core21\kedacore\sample-netcore-keda-rabbitmq\Send\Send.cs:line 16**

I'm using Docker for windows desktop with WSL2
Can you please help in this regard?

**Comment by VenkateshSrini** [comment]
I think happens when docker is put in WSL2 when I changed to Hyper v backed it started working.

**Comment by arnab-r3** [comment]
I am facing with kind too.
